- hosts: sachin
  connection: ssh
  become: yes
  become_user: root
  remote_user: sysops
  gather_facts: yes
 
  tasks:
    - name: Apache Install 
      yum: name=mysql++.x86_64  state=latest
    - name: firewall start
      service:
        name: firewalld
        state: stopped

