- hosts: all
  connection: ssh
  remote_user: sysops
  become: yes
  tasks:
   - name: reset password
     user:
      name: '{{item}}'
      update_password: always
      password: $6$Az/ObpzOaERLD79Q$/1Axs2sUgfRe.uhqS4uIjnONX7YINi6NssxItWEAGsToH1ln.1LNN2eK3B/bAYbdMAKTklLRYmkX1BLvVyZns.

     with_items:
      - root

...
