- hosts: all
  connection: ssh
  remote_user: sysops
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: update packages
      yum: name="*" state=latest disable_gpg_check=yes

