---
- hosts: all
  connection: ssh
  remote_user: sysops
  become: true
  tasks:
   - name: Install SNMP Package
     yum:
       name: "{{ packages }}"
     vars:
       packages:
         - net-snmp-utils
         - net-snmp 
       state: present  
   - name: Stop service snmpd
     service:
       name: snmpd 
       state: stopped
   - name: Copy SNMP file
     template:
       src: snmpd.conf.j2
       dest: /etc/snmp/snmpd.conf
       backup: yes
       owner: root
       group: root
       mode: '0644'
   - name: SNMPV3 User Creation
     command: 'net-snmp-create-v3-user -ro -A Pubtech123_ -X Pubtech123_ -a MD5 -x DES sgipnetv3'
   - name: Start service snmpd
     service:
       name: snmpd
       state: started
       enabled: yes
