---
- name: Creating sysops user
  hosts: sysops
  remote_user: sysops
  become: yes
  tasks:
  #- name: Creating .ssh dir
   # file:
   #  state: directory
   #  path: /home/sysops/.ssh
   #  owner: sysops
   #  group: sysops
   #  mode: 0700

  #- name: Creating authorized key file and copying public key to .ssh dir
   # copy:
    # src: /home/sysops/.ssh/id_rsa.pub
    # dest: /home/sysops/.ssh/authorized_keys
    # owner: sysops
    # group: sysops
    # mode: 0600

  - name: Assinging sudo access to sysops user
    lineinfile:
     path: /etc/sudoers
     state: present
     line: '%sysops ALL=(ALL) NOPASSWD: ALL'
     validate: '/usr/sbin/visudo -cf %s'
...

